=== BikramGyawali/BCA-All-Notes/Third Semester/Labsheet/web lab/code/14schema.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSCHEMA">
<xs:element name="Employee">
<xs:complexType>
<xs:sequence>
<xs:element name="Name">
<xs:complexType>
<xs:sequence>
<xs:element name="FirstName" type="xs:string"/>
<xs:element name="LastName" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="Contact" >
<xs:complexType>
<xs:sequence>
<xs:element name="MobileNo" type="xs:integer"/>
<xs:element name="LandLine" type="xs:integer"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="Address">
<xs:complexType>
<xs:sequence>
<xs:element name="City" type="xs:string"/>
<xs:element name="Street" type="xs:string"/>
<xs:element name="Tole" type="xs:string"/>

</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== BikramGyawali/BCA-All-Notes/Third Semester/Labsheet/web lab/code/lab.xml
<?xml version='1.0' encoding="UTF-8"?>

<Employee xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="14schema.xsd">
    <Name>
        <FirstName>John</FirstName>
        <LastName>Doe</LastName>
    </Name>
    <Contact>
        <MobileNo>1234567890</MobileNo>
        <LandLine>0987654321</LandLine>
    </Contact>
    <Address>
        <City>New York</City>
        <Street>Main St</Street>
        <Tole>Downtown</Tole>
    </Address>
</Employee>
